### ISSUE TITLE
Fail to pick path when any of the keys has dot

### ISSUE THREAD

**Issue by radmen** [JFryy/keytrail.nvim#2]
I'm using Laravel Sail and the `docker-compose.yml` it generates puts a dot in the service names:

```yaml
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
```

When using `:KeyJumpTrail` and selecting any path within `laravel.test`, this will fail with:

```
Failed to find segment: laravel
```

I guess this might be an obscure case, but it's the very first thing which happened to me when testing the extension :)
I'm still going to use it though, I think it's going to help me a ton. Thank you!
